spring.application.name=prenotazione_viaggi
spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/prenotazione_viaggi_auth
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


cloudinary.cloud_name=dkbb0gv6r
cloudinary.api_key=427541421489138
cloudinary.api_secret=Manehjnar0YsyQx7WeMnLfnexhU